[package]
name = "jit"
version = "0.1.0"
authors = ["theor <theo.richart@gmail.com>"]
edition = "2018"

[dependencies]
executable_memory = "*"
log = {version = "*", features = ["release_max_level_off"] }
# env_logger = "*"
pretty_env_logger = "*"